/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Formularios.Inventario;
import Formularios.Ventas;
import Modelo.dto.HistoriaVenta;
import Modelo.dto.Producto;
import java.util.ArrayList; 

/**
 *
 * @author diazq
 */
public class VentanaReportes extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaReportes.class.getName());
    
    // 1. Declarar variables internas (para guardar las listas recibidas)
    private ArrayList<Producto> listaGeneralP; 
    private ArrayList<HistoriaVenta> listaGeneralV; // O listaHistorial, usa el nombre que tengas en Principal.java

    // 2. Constructor MODIFICADO
    public VentanaReportes(ArrayList<Producto> listaProductos, ArrayList<HistoriaVenta> listaVentas) {
        initComponents();
        this.listaGeneralV = listaVentas;
        this.listaGeneralP = listaProductos;
        }
    

    /**
     * Creates new form VentanaReportes
     */
    public VentanaReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnExportarInventario = new javax.swing.JButton();
        btnExportarAgotados = new javax.swing.JButton();
        btnExportarVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnVolver.setBackground(new java.awt.Color(255, 204, 204));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnExportarInventario.setBackground(new java.awt.Color(255, 204, 204));
        btnExportarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inventario Actualizado.png"))); // NOI18N
        btnExportarInventario.setText("Inventario actualizado");
        btnExportarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarInventarioActionPerformed(evt);
            }
        });

        btnExportarAgotados.setBackground(new java.awt.Color(255, 204, 204));
        btnExportarAgotados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bajo Stock.jpg"))); // NOI18N
        btnExportarAgotados.setText("Productos con bajo stock");
        btnExportarAgotados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarAgotadosActionPerformed(evt);
            }
        });

        btnExportarVentas.setBackground(new java.awt.Color(255, 204, 204));
        btnExportarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ventas_1.png"))); // NOI18N
        btnExportarVentas.setText("Ventas realizadas");
        btnExportarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExportarAgotados)
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExportarVentas)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExportarInventario)
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnExportarVentas))
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportarAgotados)
                    .addComponent(btnExportarInventario))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarInventarioActionPerformed
        Inventario vInventario = new Inventario(this.listaGeneralP);
        vInventario.setVisible(true);
        vInventario.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnExportarInventarioActionPerformed

    private void btnExportarAgotadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarAgotadosActionPerformed
        BajoStock bajoStock = new BajoStock(this.listaGeneralP);
        bajoStock.setVisible(true);
        bajoStock.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnExportarAgotadosActionPerformed

    private void btnExportarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarVentasActionPerformed
        Ventas hVentas = new Ventas(this.listaGeneralV);
        hVentas.setVisible(true);
        hVentas.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnExportarVentasActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarAgotados;
    private javax.swing.JButton btnExportarInventario;
    private javax.swing.JButton btnExportarVentas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
